apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: new-secret
  namespace: default
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secret-store
    kind: SecretStore
  target:
    name: samir
    creationPolicy: Owner
  data:
  - secretKey: new-secret
    remoteRef:
      key: "/dev/waleed"
      property: "samir"