apiVersion: gitops.weave.works/v1alpha1
kind: GitopsCluster
metadata:
  annotations:
    metadata.weave.works/dashboard.prometheus: https://prometheus.io/
    weave.works/sops-key-comment: sops secret comment
    weave.works/sops-key-name: test.yourdomain.com
    weave.works/sops-kustomization: my-secrets
    weave.works/sops-push-to-git: true
    weave.works/sops-secret-ref: sops-gpg
    weave.works/sops-secret-ref-namespace: flux-system
    templates.weave.works/create-request: "{\"repository_url\":\"https://github.com/waleedhammam/wge-dev\",\"head_branch\":\"wge-create-branch-vjn7a\",\"title\":\"Create resource demo1\",\"description\":\"This PR creates a sops-cluster-template-development instance\",\"template_name\":\"sops-cluster-template-development\",\"parameter_values\":{\"CLUSTER_NAME\":\"demo1\",\"CONTROL_PLANE_MACHINE_COUNT\":\"1\",\"KUBERNETES_VERSION\":\"1.22.0\",\"NAMESPACE\":\"default\",\"SOPS_KEY_COMMENT\":\"sops secret comment\",\"SOPS_KEY_NAME\":\"test.yourdomain.com\",\"SOPS_KUSTOMIZATION_NAME\":\"my-secrets\",\"SOPS_PUSH_TO_GIT\":\"true\",\"SOPS_SECRET_REF\":\"sops-gpg\",\"SOPS_SECRET_REF_NAMESPACE\":\"flux-system\",\"WORKER_MACHINE_COUNT\":\"1\"},\"commit_message\":\"Create sops-cluster-template-development instance\",\"credentials\":{},\"template_namespace\":\"default\",\"template_kind\":\"CAPITemplate\"}"
  labels:
    templates.weave.works/template-name: sops-cluster-template-development
    templates.weave.works/template-namespace: default
    weave.works/apps: capd
    weave.works/flux: bootstrap
  name: demo1
  namespace: default
spec:
  capiClusterRef:
    name: demo1

---
apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  labels:
    cni: calico
    secretmanager: aws
    templates.weave.works/template-name: sops-cluster-template-development
    templates.weave.works/template-namespace: default
  name: demo1
  namespace: default
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
      - 192.168.0.0/16
    serviceDomain: cluster.local
    services:
      cidrBlocks:
      - 10.128.0.0/12
  controlPlaneRef:
    apiVersion: controlplane.cluster.x-k8s.io/v1beta1
    kind: KubeadmControlPlane
    name: demo1-control-plane
    namespace: default
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
    kind: DockerCluster
    name: demo1
    namespace: default

---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: DockerCluster
metadata:
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
    templates.weave.works/create-request: "{\"repository_url\":\"https://github.com/waleedhammam/wge-dev\",\"head_branch\":\"wge-create-branch-vjn7a\",\"title\":\"Create resource demo1\",\"description\":\"This PR creates a sops-cluster-template-development instance\",\"template_name\":\"sops-cluster-template-development\",\"parameter_values\":{\"CLUSTER_NAME\":\"demo1\",\"CONTROL_PLANE_MACHINE_COUNT\":\"1\",\"KUBERNETES_VERSION\":\"1.22.0\",\"NAMESPACE\":\"default\",\"SOPS_KEY_COMMENT\":\"sops secret comment\",\"SOPS_KEY_NAME\":\"test.yourdomain.com\",\"SOPS_KUSTOMIZATION_NAME\":\"my-secrets\",\"SOPS_PUSH_TO_GIT\":\"true\",\"SOPS_SECRET_REF\":\"sops-gpg\",\"SOPS_SECRET_REF_NAMESPACE\":\"flux-system\",\"WORKER_MACHINE_COUNT\":\"1\"},\"commit_message\":\"Create sops-cluster-template-development instance\",\"credentials\":{},\"template_namespace\":\"default\",\"template_kind\":\"CAPITemplate\"}"
  labels:
    templates.weave.works/template-name: sops-cluster-template-development
    templates.weave.works/template-namespace: default
  name: demo1
  namespace: default

---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: DockerMachineTemplate
metadata:
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
    templates.weave.works/create-request: "{\"repository_url\":\"https://github.com/waleedhammam/wge-dev\",\"head_branch\":\"wge-create-branch-vjn7a\",\"title\":\"Create resource demo1\",\"description\":\"This PR creates a sops-cluster-template-development instance\",\"template_name\":\"sops-cluster-template-development\",\"parameter_values\":{\"CLUSTER_NAME\":\"demo1\",\"CONTROL_PLANE_MACHINE_COUNT\":\"1\",\"KUBERNETES_VERSION\":\"1.22.0\",\"NAMESPACE\":\"default\",\"SOPS_KEY_COMMENT\":\"sops secret comment\",\"SOPS_KEY_NAME\":\"test.yourdomain.com\",\"SOPS_KUSTOMIZATION_NAME\":\"my-secrets\",\"SOPS_PUSH_TO_GIT\":\"true\",\"SOPS_SECRET_REF\":\"sops-gpg\",\"SOPS_SECRET_REF_NAMESPACE\":\"flux-system\",\"WORKER_MACHINE_COUNT\":\"1\"},\"commit_message\":\"Create sops-cluster-template-development instance\",\"credentials\":{},\"template_namespace\":\"default\",\"template_kind\":\"CAPITemplate\"}"
  labels:
    templates.weave.works/template-name: sops-cluster-template-development
    templates.weave.works/template-namespace: default
  name: demo1-control-plane
  namespace: default
spec:
  template:
    spec:
      extraMounts:
      - containerPath: /var/run/docker.sock
        hostPath: /var/run/docker.sock

---
apiVersion: controlplane.cluster.x-k8s.io/v1beta1
kind: KubeadmControlPlane
metadata:
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
    templates.weave.works/create-request: "{\"repository_url\":\"https://github.com/waleedhammam/wge-dev\",\"head_branch\":\"wge-create-branch-vjn7a\",\"title\":\"Create resource demo1\",\"description\":\"This PR creates a sops-cluster-template-development instance\",\"template_name\":\"sops-cluster-template-development\",\"parameter_values\":{\"CLUSTER_NAME\":\"demo1\",\"CONTROL_PLANE_MACHINE_COUNT\":\"1\",\"KUBERNETES_VERSION\":\"1.22.0\",\"NAMESPACE\":\"default\",\"SOPS_KEY_COMMENT\":\"sops secret comment\",\"SOPS_KEY_NAME\":\"test.yourdomain.com\",\"SOPS_KUSTOMIZATION_NAME\":\"my-secrets\",\"SOPS_PUSH_TO_GIT\":\"true\",\"SOPS_SECRET_REF\":\"sops-gpg\",\"SOPS_SECRET_REF_NAMESPACE\":\"flux-system\",\"WORKER_MACHINE_COUNT\":\"1\"},\"commit_message\":\"Create sops-cluster-template-development instance\",\"credentials\":{},\"template_namespace\":\"default\",\"template_kind\":\"CAPITemplate\"}"
  labels:
    templates.weave.works/template-name: sops-cluster-template-development
    templates.weave.works/template-namespace: default
  name: demo1-control-plane
  namespace: default
spec:
  kubeadmConfigSpec:
    clusterConfiguration:
      apiServer:
        certSANs:
        - localhost
        - 127.0.0.1
        - 0.0.0.0
      controllerManager:
        extraArgs:
          enable-hostpath-provisioner: "true"
    initConfiguration:
      nodeRegistration:
        criSocket: /var/run/containerd/containerd.sock
        kubeletExtraArgs:
          cgroup-driver: cgroupfs
          eviction-hard: nodefs.available<0%,nodefs.inodesFree<0%,imagefs.available<0%
    joinConfiguration:
      nodeRegistration:
        criSocket: /var/run/containerd/containerd.sock
        kubeletExtraArgs:
          cgroup-driver: cgroupfs
          eviction-hard: nodefs.available<0%,nodefs.inodesFree<0%,imagefs.available<0%
  machineTemplate:
    infrastructureRef:
      apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
      kind: DockerMachineTemplate
      name: demo1-control-plane
      namespace: default
  replicas: 1
  version: 1.22.0

---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: DockerMachineTemplate
metadata:
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
    templates.weave.works/create-request: "{\"repository_url\":\"https://github.com/waleedhammam/wge-dev\",\"head_branch\":\"wge-create-branch-vjn7a\",\"title\":\"Create resource demo1\",\"description\":\"This PR creates a sops-cluster-template-development instance\",\"template_name\":\"sops-cluster-template-development\",\"parameter_values\":{\"CLUSTER_NAME\":\"demo1\",\"CONTROL_PLANE_MACHINE_COUNT\":\"1\",\"KUBERNETES_VERSION\":\"1.22.0\",\"NAMESPACE\":\"default\",\"SOPS_KEY_COMMENT\":\"sops secret comment\",\"SOPS_KEY_NAME\":\"test.yourdomain.com\",\"SOPS_KUSTOMIZATION_NAME\":\"my-secrets\",\"SOPS_PUSH_TO_GIT\":\"true\",\"SOPS_SECRET_REF\":\"sops-gpg\",\"SOPS_SECRET_REF_NAMESPACE\":\"flux-system\",\"WORKER_MACHINE_COUNT\":\"1\"},\"commit_message\":\"Create sops-cluster-template-development instance\",\"credentials\":{},\"template_namespace\":\"default\",\"template_kind\":\"CAPITemplate\"}"
  labels:
    templates.weave.works/template-name: sops-cluster-template-development
    templates.weave.works/template-namespace: default
  name: demo1-md-0
  namespace: default
spec:
  template:
    spec: {}

---
apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
kind: KubeadmConfigTemplate
metadata:
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
    templates.weave.works/create-request: "{\"repository_url\":\"https://github.com/waleedhammam/wge-dev\",\"head_branch\":\"wge-create-branch-vjn7a\",\"title\":\"Create resource demo1\",\"description\":\"This PR creates a sops-cluster-template-development instance\",\"template_name\":\"sops-cluster-template-development\",\"parameter_values\":{\"CLUSTER_NAME\":\"demo1\",\"CONTROL_PLANE_MACHINE_COUNT\":\"1\",\"KUBERNETES_VERSION\":\"1.22.0\",\"NAMESPACE\":\"default\",\"SOPS_KEY_COMMENT\":\"sops secret comment\",\"SOPS_KEY_NAME\":\"test.yourdomain.com\",\"SOPS_KUSTOMIZATION_NAME\":\"my-secrets\",\"SOPS_PUSH_TO_GIT\":\"true\",\"SOPS_SECRET_REF\":\"sops-gpg\",\"SOPS_SECRET_REF_NAMESPACE\":\"flux-system\",\"WORKER_MACHINE_COUNT\":\"1\"},\"commit_message\":\"Create sops-cluster-template-development instance\",\"credentials\":{},\"template_namespace\":\"default\",\"template_kind\":\"CAPITemplate\"}"
  labels:
    templates.weave.works/template-name: sops-cluster-template-development
    templates.weave.works/template-namespace: default
  name: demo1-md-0
  namespace: default
spec:
  template:
    spec:
      joinConfiguration:
        nodeRegistration:
          kubeletExtraArgs:
            cgroup-driver: cgroupfs
            eviction-hard: nodefs.available<0%,nodefs.inodesFree<0%,imagefs.available<0%

---
apiVersion: cluster.x-k8s.io/v1beta1
kind: MachineDeployment
metadata:
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
    templates.weave.works/create-request: "{\"repository_url\":\"https://github.com/waleedhammam/wge-dev\",\"head_branch\":\"wge-create-branch-vjn7a\",\"title\":\"Create resource demo1\",\"description\":\"This PR creates a sops-cluster-template-development instance\",\"template_name\":\"sops-cluster-template-development\",\"parameter_values\":{\"CLUSTER_NAME\":\"demo1\",\"CONTROL_PLANE_MACHINE_COUNT\":\"1\",\"KUBERNETES_VERSION\":\"1.22.0\",\"NAMESPACE\":\"default\",\"SOPS_KEY_COMMENT\":\"sops secret comment\",\"SOPS_KEY_NAME\":\"test.yourdomain.com\",\"SOPS_KUSTOMIZATION_NAME\":\"my-secrets\",\"SOPS_PUSH_TO_GIT\":\"true\",\"SOPS_SECRET_REF\":\"sops-gpg\",\"SOPS_SECRET_REF_NAMESPACE\":\"flux-system\",\"WORKER_MACHINE_COUNT\":\"1\"},\"commit_message\":\"Create sops-cluster-template-development instance\",\"credentials\":{},\"template_namespace\":\"default\",\"template_kind\":\"CAPITemplate\"}"
  labels:
    templates.weave.works/template-name: sops-cluster-template-development
    templates.weave.works/template-namespace: default
  name: demo1-md-0
  namespace: default
spec:
  clusterName: demo1
  replicas: 1
  selector:
    matchLabels: null
  template:
    spec:
      bootstrap:
        configRef:
          apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
          kind: KubeadmConfigTemplate
          name: demo1-md-0
          namespace: default
      clusterName: demo1
      infrastructureRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
        kind: DockerMachineTemplate
        name: demo1-md-0
        namespace: default
      version: 1.22.0
