apiVersion: gitops.weave.works/v1alpha1
kind: GitopsCluster
metadata:
  labels:
    templates.weave.works/template-name: cluster-template-development
    templates.weave.works/template-namespace: default
    weave.works/capi: bootstrap
  name: empty
  namespace: default
  annotations:
    templates.weave.works/create-request: "{\"repository_url\":\"https://github.com/waleedhammam/wge-dev\",\"head_branch\":\"wge-create-branch-ghhju9\",\"title\":\"Create resource empty\",\"description\":\"This PR creates a cluster-template-development instance\",\"template_name\":\"cluster-template-development\",\"parameter_values\":{\"CLUSTER_NAME\":\"empty\",\"CONTROL_PLANE_MACHINE_COUNT\":\"1\",\"KUBERNETES_VERSION\":\"1.22.0\",\"NAMESPACE\":\"default\",\"WORKER_MACHINE_COUNT\":\"1\"},\"commit_message\":\"Create cluster-template-development instance\",\"credentials\":{},\"values\":[{\"name\":\"cert-manager\",\"version\":\"0.0.8\",\"layer\":\"layer-0\",\"namespace\":\"cert-manager\"}],\"template_namespace\":\"default\",\"template_kind\":\"GitOpsTemplate\"}"
spec:
  capiClusterRef:
    name: empty

---
apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  labels:
    cni: calico
    templates.weave.works/template-name: cluster-template-development
    templates.weave.works/template-namespace: default
  name: empty
  namespace: default
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
      - 192.168.0.0/16
    serviceDomain: cluster.local
    services:
      cidrBlocks:
      - 10.128.0.0/12
  controlPlaneRef:
    apiVersion: controlplane.cluster.x-k8s.io/v1beta1
    kind: KubeadmControlPlane
    name: empty-control-plane
    namespace: default
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
    kind: DockerCluster
    name: empty
    namespace: default

---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: DockerCluster
metadata:
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
    templates.weave.works/create-request: "{\"repository_url\":\"https://github.com/waleedhammam/wge-dev\",\"head_branch\":\"wge-create-branch-ghhju9\",\"title\":\"Create resource empty\",\"description\":\"This PR creates a cluster-template-development instance\",\"template_name\":\"cluster-template-development\",\"parameter_values\":{\"CLUSTER_NAME\":\"empty\",\"CONTROL_PLANE_MACHINE_COUNT\":\"1\",\"KUBERNETES_VERSION\":\"1.22.0\",\"NAMESPACE\":\"default\",\"WORKER_MACHINE_COUNT\":\"1\"},\"commit_message\":\"Create cluster-template-development instance\",\"credentials\":{},\"values\":[{\"name\":\"cert-manager\",\"version\":\"0.0.8\",\"layer\":\"layer-0\",\"namespace\":\"cert-manager\"}],\"template_namespace\":\"default\",\"template_kind\":\"GitOpsTemplate\"}"
  labels:
    templates.weave.works/template-name: cluster-template-development
    templates.weave.works/template-namespace: default
  name: empty
  namespace: default

---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: DockerMachineTemplate
metadata:
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
    templates.weave.works/create-request: "{\"repository_url\":\"https://github.com/waleedhammam/wge-dev\",\"head_branch\":\"wge-create-branch-ghhju9\",\"title\":\"Create resource empty\",\"description\":\"This PR creates a cluster-template-development instance\",\"template_name\":\"cluster-template-development\",\"parameter_values\":{\"CLUSTER_NAME\":\"empty\",\"CONTROL_PLANE_MACHINE_COUNT\":\"1\",\"KUBERNETES_VERSION\":\"1.22.0\",\"NAMESPACE\":\"default\",\"WORKER_MACHINE_COUNT\":\"1\"},\"commit_message\":\"Create cluster-template-development instance\",\"credentials\":{},\"values\":[{\"name\":\"cert-manager\",\"version\":\"0.0.8\",\"layer\":\"layer-0\",\"namespace\":\"cert-manager\"}],\"template_namespace\":\"default\",\"template_kind\":\"GitOpsTemplate\"}"
  labels:
    templates.weave.works/template-name: cluster-template-development
    templates.weave.works/template-namespace: default
  name: empty-control-plane
  namespace: default
spec:
  template:
    spec:
      extraMounts:
      - containerPath: /var/run/docker.sock
        hostPath: /var/run/docker.sock

---
apiVersion: controlplane.cluster.x-k8s.io/v1beta1
kind: KubeadmControlPlane
metadata:
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
    templates.weave.works/create-request: "{\"repository_url\":\"https://github.com/waleedhammam/wge-dev\",\"head_branch\":\"wge-create-branch-ghhju9\",\"title\":\"Create resource empty\",\"description\":\"This PR creates a cluster-template-development instance\",\"template_name\":\"cluster-template-development\",\"parameter_values\":{\"CLUSTER_NAME\":\"empty\",\"CONTROL_PLANE_MACHINE_COUNT\":\"1\",\"KUBERNETES_VERSION\":\"1.22.0\",\"NAMESPACE\":\"default\",\"WORKER_MACHINE_COUNT\":\"1\"},\"commit_message\":\"Create cluster-template-development instance\",\"credentials\":{},\"values\":[{\"name\":\"cert-manager\",\"version\":\"0.0.8\",\"layer\":\"layer-0\",\"namespace\":\"cert-manager\"}],\"template_namespace\":\"default\",\"template_kind\":\"GitOpsTemplate\"}"
  labels:
    templates.weave.works/template-name: cluster-template-development
    templates.weave.works/template-namespace: default
  name: empty-control-plane
  namespace: default
spec:
  kubeadmConfigSpec:
    clusterConfiguration:
      apiServer:
        certSANs:
        - localhost
        - 127.0.0.1
        - 0.0.0.0
      controllerManager:
        extraArgs:
          enable-hostpath-provisioner: "true"
    initConfiguration:
      nodeRegistration:
        criSocket: /var/run/containerd/containerd.sock
        kubeletExtraArgs:
          cgroup-driver: cgroupfs
          eviction-hard: nodefs.available<0%,nodefs.inodesFree<0%,imagefs.available<0%
    joinConfiguration:
      nodeRegistration:
        criSocket: /var/run/containerd/containerd.sock
        kubeletExtraArgs:
          cgroup-driver: cgroupfs
          eviction-hard: nodefs.available<0%,nodefs.inodesFree<0%,imagefs.available<0%
  machineTemplate:
    infrastructureRef:
      apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
      kind: DockerMachineTemplate
      name: empty-control-plane
      namespace: default
  replicas: 1
  version: 1.22.0

---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: DockerMachineTemplate
metadata:
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
    templates.weave.works/create-request: "{\"repository_url\":\"https://github.com/waleedhammam/wge-dev\",\"head_branch\":\"wge-create-branch-ghhju9\",\"title\":\"Create resource empty\",\"description\":\"This PR creates a cluster-template-development instance\",\"template_name\":\"cluster-template-development\",\"parameter_values\":{\"CLUSTER_NAME\":\"empty\",\"CONTROL_PLANE_MACHINE_COUNT\":\"1\",\"KUBERNETES_VERSION\":\"1.22.0\",\"NAMESPACE\":\"default\",\"WORKER_MACHINE_COUNT\":\"1\"},\"commit_message\":\"Create cluster-template-development instance\",\"credentials\":{},\"values\":[{\"name\":\"cert-manager\",\"version\":\"0.0.8\",\"layer\":\"layer-0\",\"namespace\":\"cert-manager\"}],\"template_namespace\":\"default\",\"template_kind\":\"GitOpsTemplate\"}"
  labels:
    templates.weave.works/template-name: cluster-template-development
    templates.weave.works/template-namespace: default
  name: empty-md-0
  namespace: default
spec:
  template:
    spec: {}

---
apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
kind: KubeadmConfigTemplate
metadata:
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
    templates.weave.works/create-request: "{\"repository_url\":\"https://github.com/waleedhammam/wge-dev\",\"head_branch\":\"wge-create-branch-ghhju9\",\"title\":\"Create resource empty\",\"description\":\"This PR creates a cluster-template-development instance\",\"template_name\":\"cluster-template-development\",\"parameter_values\":{\"CLUSTER_NAME\":\"empty\",\"CONTROL_PLANE_MACHINE_COUNT\":\"1\",\"KUBERNETES_VERSION\":\"1.22.0\",\"NAMESPACE\":\"default\",\"WORKER_MACHINE_COUNT\":\"1\"},\"commit_message\":\"Create cluster-template-development instance\",\"credentials\":{},\"values\":[{\"name\":\"cert-manager\",\"version\":\"0.0.8\",\"layer\":\"layer-0\",\"namespace\":\"cert-manager\"}],\"template_namespace\":\"default\",\"template_kind\":\"GitOpsTemplate\"}"
  labels:
    templates.weave.works/template-name: cluster-template-development
    templates.weave.works/template-namespace: default
  name: empty-md-0
  namespace: default
spec:
  template:
    spec:
      joinConfiguration:
        nodeRegistration:
          kubeletExtraArgs:
            cgroup-driver: cgroupfs
            eviction-hard: nodefs.available<0%,nodefs.inodesFree<0%,imagefs.available<0%

---
apiVersion: cluster.x-k8s.io/v1beta1
kind: MachineDeployment
metadata:
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
    templates.weave.works/create-request: "{\"repository_url\":\"https://github.com/waleedhammam/wge-dev\",\"head_branch\":\"wge-create-branch-ghhju9\",\"title\":\"Create resource empty\",\"description\":\"This PR creates a cluster-template-development instance\",\"template_name\":\"cluster-template-development\",\"parameter_values\":{\"CLUSTER_NAME\":\"empty\",\"CONTROL_PLANE_MACHINE_COUNT\":\"1\",\"KUBERNETES_VERSION\":\"1.22.0\",\"NAMESPACE\":\"default\",\"WORKER_MACHINE_COUNT\":\"1\"},\"commit_message\":\"Create cluster-template-development instance\",\"credentials\":{},\"values\":[{\"name\":\"cert-manager\",\"version\":\"0.0.8\",\"layer\":\"layer-0\",\"namespace\":\"cert-manager\"}],\"template_namespace\":\"default\",\"template_kind\":\"GitOpsTemplate\"}"
  labels:
    templates.weave.works/template-name: cluster-template-development
    templates.weave.works/template-namespace: default
  name: empty-md-0
  namespace: default
spec:
  clusterName: empty
  replicas: 1
  selector:
    matchLabels: null
  template:
    spec:
      bootstrap:
        configRef:
          apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
          kind: KubeadmConfigTemplate
          name: empty-md-0
          namespace: default
      clusterName: empty
      infrastructureRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
        kind: DockerMachineTemplate
        name: empty-md-0
        namespace: default
      version: 1.22.0
