apiVersion: gitops.weave.works/v1alpha1
kind: GitopsCluster
metadata:
  annotations:
    metadata.weave.works/dashboard.prometheus: https://prometheus.io/
    templates.weave.works/create-request: '{"repository_url":"https://github.com/waleedhammam/wge-dev","head_branch":"wge-create-branch-a4408o","title":"Creates
      resource leaf-111","description":"This PR creates a waleed-cluster-template-development
      instance","template_name":"waleed-cluster-template-development","parameter_values":{"CLUSTER_NAME":"leaf-111","CONTROL_PLANE_MACHINE_COUNT":"1","KUBERNETES_VERSION":"1.23.3","NAMESPACE":"default","WORKER_MACHINE_COUNT":"1"},"commit_message":"Creates
      waleed-cluster-template-development instance","credentials":{},"values":[{"name":"external-secrets","version":"0.6.1","values":"ZXh0ZXJuYWwtc2VjcmV0czoKICBpbnN0YWxsQ1JEczogdHJ1ZQoKc2VjcmV0c1NvdXJjZToKICBlbmFibGVkOiB0cnVlCiAgdXJsOiBzc2g6Ly9naXRAZ2l0aHViLmNvbS93YWxlZWRoYW1tYW0vd2dlLWRldiAgICAjIHVybCBmb3IgdGhlIGdpdCByZXBvc2l0b3J5IHRoYXQgY29udGFpbnMgdGhlIFNlY3JldFN0b3JlLCBFeHRlcm5hbFNlY3JldHMgQ1JzCiAgIyB0YWc6IHYxLjAuMCAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIyBpZiB5b3Ugd291bGQgbGlrZSB0byBkb3dubG9hZCB5b3VyIHNlY3JldHMgZnJvbSBzcGVjaWZpYyB0YWcKICBicmFuY2g6IG1haW4gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAjIGlmIHlvdSB3b3VsZCBsaWtlIHRvIGRvd25sb2FkIHlvdXIgc2VjcmV0cyBmcm9tIHNwZWNpZmljIGJyYW5jaAogIHBhdGg6IC4vY2x1c3RlcnMvc2VjcmV0cy9tYW5hZ2VtZW50LyAgICAgICAgICAgICMgY291bGQgYmUgYSBwYXRoIHRvIHRoZSBzZWNyZXRzIGRpciBvciBhIGt1c3RvbWl6YXRpb24ueWFtbCBmaWxlIGZvciB0aGUgQ1JzIChTZWNyZXRTdG9yZSwgRXh0ZXJuYWxTZWNyZXQpIGluIHRoZSBHaXRSZXBvc2l0b3J5CiAgc2VjcmV0UmVmOiBzc2gtY3JlZHMgICAgICAgICAgICAgICAgICAgICAgICAgICAgIyBOYW1lIG9mIHRoZSBLOHMgc2VjcmV0IHdpdGggcHJpdmF0ZSByZXBvIGF1dGggY3JlZGVudGlhbHMgKHByaXZhdGUga2V5LCBwdWIga2V5LCBrbm93biBob3N0cykKICAjIHNvdXJjZVJlZjogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAjIENvdWxkIHNwZWNpZnkgYSBuYW1lIGZvciBhbiBleGlzdGluZyBHaXRTb3VyY2UgcmVmZXJlbmNlIGluc3RlYWQgb2YgY3JlYXRpbmcgYSBuZXcgb25lCiAgIyAgIGtpbmQ6IEdpdFJlcG9zaXRvcnkKICAjICAgbmFtZTogZXh0ZXJuYWwtc2VjcmV0cwogICMgICBuYW1lc3BhY2U6IGV4dGVybmFsLXNlY3JldHMK","layer":"layer-0","namespace":"external-secrets"}],"template_namespace":"default","template_kind":"CAPITemplate"}'
  labels:
    templates.weave.works/template-name: waleed-cluster-template-development
    templates.weave.works/template-namespace: default
    weave.works/apps: capd
    weave.works/flux: bootstrap
  name: leaf-111
  namespace: default
spec:
  capiClusterRef:
    name: leaf-111

---
apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  labels:
    cni: calico
    secretmanager: aws
    templates.weave.works/template-name: waleed-cluster-template-development
    templates.weave.works/template-namespace: default
  name: leaf-111
  namespace: default
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
      - 192.168.0.0/16
    serviceDomain: cluster.local
    services:
      cidrBlocks:
      - 10.128.0.0/12
  controlPlaneRef:
    apiVersion: controlplane.cluster.x-k8s.io/v1beta1
    kind: KubeadmControlPlane
    name: leaf-111-control-plane
    namespace: default
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
    kind: DockerCluster
    name: leaf-111
    namespace: default

---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: DockerCluster
metadata:
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
  labels:
    templates.weave.works/template-name: waleed-cluster-template-development
    templates.weave.works/template-namespace: default
  name: leaf-111
  namespace: default

---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: DockerMachineTemplate
metadata:
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
  labels:
    templates.weave.works/template-name: waleed-cluster-template-development
    templates.weave.works/template-namespace: default
  name: leaf-111-control-plane
  namespace: default
spec:
  template:
    spec:
      extraMounts:
      - containerPath: /var/run/docker.sock
        hostPath: /var/run/docker.sock

---
apiVersion: controlplane.cluster.x-k8s.io/v1beta1
kind: KubeadmControlPlane
metadata:
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
  labels:
    templates.weave.works/template-name: waleed-cluster-template-development
    templates.weave.works/template-namespace: default
  name: leaf-111-control-plane
  namespace: default
spec:
  kubeadmConfigSpec:
    clusterConfiguration:
      apiServer:
        certSANs:
        - localhost
        - 127.0.0.1
        - 0.0.0.0
      controllerManager:
        extraArgs:
          enable-hostpath-provisioner: "true"
    initConfiguration:
      nodeRegistration:
        criSocket: /var/run/containerd/containerd.sock
        kubeletExtraArgs:
          cgroup-driver: cgroupfs
          eviction-hard: nodefs.available<0%,nodefs.inodesFree<0%,imagefs.available<0%
    joinConfiguration:
      nodeRegistration:
        criSocket: /var/run/containerd/containerd.sock
        kubeletExtraArgs:
          cgroup-driver: cgroupfs
          eviction-hard: nodefs.available<0%,nodefs.inodesFree<0%,imagefs.available<0%
  machineTemplate:
    infrastructureRef:
      apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
      kind: DockerMachineTemplate
      name: leaf-111-control-plane
      namespace: default
  replicas: 1
  version: 1.23.3

---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: DockerMachineTemplate
metadata:
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
  labels:
    templates.weave.works/template-name: waleed-cluster-template-development
    templates.weave.works/template-namespace: default
  name: leaf-111-md-0
  namespace: default
spec:
  template:
    spec: {}

---
apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
kind: KubeadmConfigTemplate
metadata:
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
  labels:
    templates.weave.works/template-name: waleed-cluster-template-development
    templates.weave.works/template-namespace: default
  name: leaf-111-md-0
  namespace: default
spec:
  template:
    spec:
      joinConfiguration:
        nodeRegistration:
          kubeletExtraArgs:
            cgroup-driver: cgroupfs
            eviction-hard: nodefs.available<0%,nodefs.inodesFree<0%,imagefs.available<0%

---
apiVersion: cluster.x-k8s.io/v1beta1
kind: MachineDeployment
metadata:
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
  labels:
    templates.weave.works/template-name: waleed-cluster-template-development
    templates.weave.works/template-namespace: default
  name: leaf-111-md-0
  namespace: default
spec:
  clusterName: leaf-111
  replicas: 1
  selector:
    matchLabels: null
  template:
    spec:
      bootstrap:
        configRef:
          apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
          kind: KubeadmConfigTemplate
          name: leaf-111-md-0
          namespace: default
      clusterName: leaf-111
      infrastructureRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
        kind: DockerMachineTemplate
        name: leaf-111-md-0
        namespace: default
      version: 1.23.3
