apiVersion: gitops.weave.works/v1alpha1
kind: GitopsCluster
metadata:
  annotations:
    metadata.weave.works/dashboard.prometheus: https://prometheus.io/
    templates.weave.works/create-request: '{"repository_url":"https://github.com/waleedhammam/wge-dev","head_branch":"wge-create-branch-dpyty7","title":"Creates
      resource test","description":"This PR creates a waleed-cluster-template-development
      instance","template_name":"waleed-cluster-template-development","parameter_values":{"CLUSTER_NAME":"test","CONTROL_PLANE_MACHINE_COUNT":"1","KUBERNETES_VERSION":"1.22.0","NAMESPACE":"default","SOPS_KUSTOMIZATION_GIT_REPO_NAME":"flux-system","SOPS_KUSTOMIZATION_NAME":"my-secrets","SOPS_KUSTOMIZATION_PATH_IN_GIT_REPO":"./sops","WORKER_MACHINE_COUNT":"1"},"commit_message":"Creates
      waleed-cluster-template-development instance","credentials":{},"template_namespace":"default","template_kind":"CAPITemplate"}'
    weave.works/sops-kustomization: bootstrap-my-secrets
    weave.works/sops-path: path-./sops
    weave.works/sops-repo: repo-flux-system
  labels:
    templates.weave.works/template-name: waleed-cluster-template-development
    templates.weave.works/template-namespace: default
    weave.works/apps: capd
    weave.works/flux: bootstrap
  name: test
  namespace: default
spec:
  capiClusterRef:
    name: test

---
apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  labels:
    cni: calico
    secretmanager: aws
    templates.weave.works/template-name: waleed-cluster-template-development
    templates.weave.works/template-namespace: default
  name: test
  namespace: default
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
      - 192.168.0.0/16
    serviceDomain: cluster.local
    services:
      cidrBlocks:
      - 10.128.0.0/12
  controlPlaneRef:
    apiVersion: controlplane.cluster.x-k8s.io/v1beta1
    kind: KubeadmControlPlane
    name: test-control-plane
    namespace: default
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
    kind: DockerCluster
    name: test
    namespace: default

---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: DockerCluster
metadata:
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
  labels:
    templates.weave.works/template-name: waleed-cluster-template-development
    templates.weave.works/template-namespace: default
  name: test
  namespace: default

---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: DockerMachineTemplate
metadata:
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
  labels:
    templates.weave.works/template-name: waleed-cluster-template-development
    templates.weave.works/template-namespace: default
  name: test-control-plane
  namespace: default
spec:
  template:
    spec:
      extraMounts:
      - containerPath: /var/run/docker.sock
        hostPath: /var/run/docker.sock

---
apiVersion: controlplane.cluster.x-k8s.io/v1beta1
kind: KubeadmControlPlane
metadata:
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
  labels:
    templates.weave.works/template-name: waleed-cluster-template-development
    templates.weave.works/template-namespace: default
  name: test-control-plane
  namespace: default
spec:
  kubeadmConfigSpec:
    clusterConfiguration:
      apiServer:
        certSANs:
        - localhost
        - 127.0.0.1
        - 0.0.0.0
      controllerManager:
        extraArgs:
          enable-hostpath-provisioner: "true"
    initConfiguration:
      nodeRegistration:
        criSocket: /var/run/containerd/containerd.sock
        kubeletExtraArgs:
          cgroup-driver: cgroupfs
          eviction-hard: nodefs.available<0%,nodefs.inodesFree<0%,imagefs.available<0%
    joinConfiguration:
      nodeRegistration:
        criSocket: /var/run/containerd/containerd.sock
        kubeletExtraArgs:
          cgroup-driver: cgroupfs
          eviction-hard: nodefs.available<0%,nodefs.inodesFree<0%,imagefs.available<0%
  machineTemplate:
    infrastructureRef:
      apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
      kind: DockerMachineTemplate
      name: test-control-plane
      namespace: default
  replicas: 1
  version: 1.22.0

---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: DockerMachineTemplate
metadata:
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
  labels:
    templates.weave.works/template-name: waleed-cluster-template-development
    templates.weave.works/template-namespace: default
  name: test-md-0
  namespace: default
spec:
  template:
    spec: {}

---
apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
kind: KubeadmConfigTemplate
metadata:
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
  labels:
    templates.weave.works/template-name: waleed-cluster-template-development
    templates.weave.works/template-namespace: default
  name: test-md-0
  namespace: default
spec:
  template:
    spec:
      joinConfiguration:
        nodeRegistration:
          kubeletExtraArgs:
            cgroup-driver: cgroupfs
            eviction-hard: nodefs.available<0%,nodefs.inodesFree<0%,imagefs.available<0%

---
apiVersion: cluster.x-k8s.io/v1beta1
kind: MachineDeployment
metadata:
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
  labels:
    templates.weave.works/template-name: waleed-cluster-template-development
    templates.weave.works/template-namespace: default
  name: test-md-0
  namespace: default
spec:
  clusterName: test
  replicas: 1
  selector:
    matchLabels: null
  template:
    spec:
      bootstrap:
        configRef:
          apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
          kind: KubeadmConfigTemplate
          name: test-md-0
          namespace: default
      clusterName: test
      infrastructureRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
        kind: DockerMachineTemplate
        name: test-md-0
        namespace: default
      version: 1.22.0
