apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  creationTimestamp: null
  name: policy-agent
  namespace: flux-system
spec:
  chart:
    spec:
      chart: policy-agent
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: policy-agent
        namespace: flux-system
      version: 2.5.0
  install:
    crds: CreateReplace
    createNamespace: true
  interval: 10m0s
  values:
    config:
      admission:
        enabled: false
        sinks:
          k8sEventsSink:
            enabled: true
      audit:
        enabled: true
        sinks:
          k8sEventsSink:
            enabled: true
    excludeNamespaces:
    - kube-system
    - flux-system
    failurePolicy: Fail
    useCertManager: true
status: {}
