apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  creationTimestamp: null
  labels:
    sops-public-key/name: sops-gpg-pub
    sops-public-key/namespace: flux-system
  name: my-secrets
  namespace: flux-system
spec:
  decryption:
    provider: sops
    secretRef:
      name: sops-gpg
  interval: 10m0s
  path: clusters/default/www/sops
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
status: {}
