apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  annotations:
    sops-public-key/name: sops-pub
    sops-public-key/namespace: test
  creationTimestamp: null
  name: secrets
  namespace: flux-system
spec:
  decryption:
    provider: sops
    secretRef:
      name: sops
  interval: 10m0s
  path: clusters/default/debugo/sops
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
status: {}
